name: tilt-corrected-bf-stem
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - h5py
  - matplotlib
  - k3d
  - ipympl
  - py4DSTEM
  - ipywidgets
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
  - pip
  - pip:
    - https://raw.githubusercontent.com/gvarnavi/TemGymLite/main/dist/temgymlite-0.6.0.0-py3-none-any.whl
